from time import sleep
print ("                                                             ")
print ("                 Tommes Kauf rechner                         ")
print ("                                                             ")
capital = input ("   Wieviel Kapital hast du zu verfügung? \n")
cos_stock = input ("   Was kostet die Aktie? \n")
cos1_stock = float(cos_stock)
capi = float(capital)
sum_stock = (capi * 2)/100
SL = (sum_stock * 10)/100
price = float(sum_stock) / float(cos1_stock)
print (" ")
print (" ")
print (" ")
print (" ")
print (" ")
print (" ")
print (" ")
print (" ")
print (" ")
print (" ")
print ("                                                             ")
print ("              Du kannst für " + str(sum_stock) + " Euro kaufen")
print ("              Du solltest bei " + str(SL) + " Euro verkaufen")
print ("              Du kannst " + str(price) + " Stück kaufen")
print ("                                                             ")
print (" ")
print (" ")
print (" ")
print (" ")
print (" ")
sleep (5) 